config/routes.rb
Quotes::Application.routes.draw do
  
  resources :quotes
  resources :tags
  resources :users do
    resources :tags
  end
  resource :session, :only => [:new, :create, :destroy]
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'get-started' => 'users#new', :as => :get_started
  match '/q/:id' => 'quotes#show', :as => :short_quote
  match '/:username' => 'users#show', :as => :short_user
  root :to => 'quotes#index'
  
  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  
  validates_presence_of :text, :message => "can't be blank"
  validates_presence_of :user_id
  
  before_save :cleanup_text
  after_save :assign_tags
  
default_scope :order => "created_at DESC"
  
  attr_accessor :tag_names
  def tag_names
    @tag_names || tags.map(&:name).join(' ')
  end
  
  private 
  
  def cleanup_text
   text.gsub!(/\A"/, '')
   text.gsub!(/\A“/, '')
   text.gsub!(/"\Z/, '')
   text.gsub!(/”\Z/, '')
  end
  
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/,+/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  respond_to :html
  before_filter :login_required, :only => [:new, :create, :edit]
  def index
    if !params[:search].nil?
      @quotes = Quote.where("text like ? or author like ?", "%#{params[:search]}%","%#{params[:search]}%")
      if @quotes.length == 0
        flash[:notice] = "No quotes found"
      end
    else
      @quotes = Quote.all    
    end
  
    respond_with(@quotes)
    
  end

  def show
    @quote = Quote.find(params[:id])
    respond_with(@quote)
  end

  def new
    @quote = current_user.quotes.build
    @quote.text = params[:t]
    @quote.author = params[:a]
    @quote.source = params[:s]
    respond_with(@quote)
  end

  def edit
    @quote = Quote.find(params[:id])
    if current_user.id != @quote.user.id
      flash[:warning] = "Sorry, you can only edit quotes you have created."
      redirect_to(@quote)
    end
  end
  
  def create
    @quote = current_user.quotes.build(params[:quote])
    if @quote.save
      flash[:notice] = 'Quote was successfully added.'
    end
    respond_with(@quote)
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update_attributes(params[:quote])
      flash[:notice] = 'Quote was successfully updated.'
    end
    respond_with(@quote)
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    respond_with(@quote)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<% if logged_in? %>
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :text, "Quote:" %><br />
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>

  <div class="field">
    <%= f.label :tag_names, "Tags" %><br />
    <%= f.text_field :tag_names %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else %>
	Please <%= link_to "login", login_path %> to post a new quote.
<% end %>

app/views/quotes/_quote.html.erb
<% content_tag :li, :class => "article quote", :id => "quote_#{quote.id}" do %>
	<%= render 'quotes/quote_content', :quote => quote %>
	<%= link_to "permalink", quote %>
<% end %>

app/views/quotes/_quote_content.html.erb
<% content_tag :blockquote, :class => "text", :cite => 	"#{quote.source}" do %> 
&#8220;&nbsp;<%= quote.text %>&nbsp;&#8221;
	<% end %>
	<%= content_tag :cite, twitify(quote.author) %>
	quoted by <%= link_to quote.user.username, short_user_path(quote.user.username) %> <%= time_ago_in_words(quote.created_at) %> ago.
<% if quote.tags.present? %>
	<ul class="tags">
		<%= render quote.tags.sort_by {|tag| tag.name} %>
	</ul>
<% end %>

app/views/quotes/_show_quote.html.erb
<% content_tag :div, :class => "article quote", :id => "quote_#{quote.id}" do %>
	<%= render 'quote_content', :quote => quote %>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<div id="feature">
	<div class="section">
	<h1>Welcome to blockq.</h1>
	<p>Here you can save and tag quotes you want to remember, search for quotes or topics, or find out what people think is worth remembering!</p>
	<%= link_to "Get started", get_started_path, {:id => "get_started"}%>
	</div>
</div>
<div class="section" id="latest_quotes">
	<h2>Latest quotes</h2>
	<ul>
		<%= render @quotes %>
	</ul>	
</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<div class="section">
<%= render 'show_quote', :quote => @quote, :user => @user %>
</div>