config/routes.rb
Quotes::Application.routes.draw do
  
  resources :quotes
  resources :tags
  resources :users do
    resources :tags
  end
  resource :session, :only => [:new, :create, :destroy]
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'get-started' => 'users#new', :as => :get_started
  match '/q/:id' => 'quotes#show', :as => :short_quote
  match '/:username' => 'users#show', :as => :short_user
  root :to => 'quotes#index'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>blockq | quotations </title>
  <%= stylesheet_link_tag :all %>
#"http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"
	<%= javascript_include_tag "jquery.min.js", "jquery.rails.js", "jquery.ligatures.js", "jquery.widowFix-1.3.1.min.js", "application.js", :as => "blockq.js" %>
<%= csrf_meta_tag %>
</head>
<% content_tag :body, :id => "#{controller.controller_name}_#{controller.action_name}" do %>
	<div id="header">
		<%= link_to "blockq", root_path %>
		<%= link_to "tags", tags_path %>
	<!--	<form>
		<input type="text" name="search"/>
		<input type="submit" value="search"/>
		</form> -->
		<%#= link_to "Get involved!", new_user_path %>
		<%= link_to 'New Quote', new_quote_path %>
		<%#= link_to "blockq bookmarklet", "javascript:(function(){document.body.appendChild(document.createElement('script')).src='http://#{request.host_with_port}/javascripts/bookmarklet.js';})();"%>
	
	</div>
	<div class="section" id="main">
		<% flash.each do |key, message |%>
			<%= content_tag :p, message, :id => "flash", :class => "#{key}" %>
		<% end %>
		<%= yield %>
	</div>
<% end %>
</html>